version: '2'
services:
  apim_rdbms:
    image: docker.wso2.com/apim-pattern4-apim_rdbms:2.1.0
    build:
        context: ../
        dockerfile: pattern-4/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  analytics:
    image: docker.wso2.com/apim-pattern4-analytics:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/am-analytics/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9448:9444"
  traffic-manager:
    image: docker.wso2.com/apim-pattern4-traffic-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/traffic-manager/Dockerfile
    environment:
      - SLEEP=60
    ports:
    - "9447:9443"
  keymanager:
    image: docker.wso2.com/apim-pattern4-keymanager:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/keymanager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9443:9443"
  gateway-manager:
    image: docker.wso2.com/apim-pattern4-gateway-manager:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    ports:
    - "9444:9443"
  gateway-worker:
    image: docker.wso2.com/apim-pattern4-gateway-worker:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/gateway-worker/Dockerfile
    environment:
      - SLEEP=230
    ports:
    - "8280:8280"
    - "8243:8243"
    links:
      - gateway-manager
  store:
    image: docker.wso2.com/apim-pattern4-store:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/store/Dockerfile
    environment:
      - SLEEP=260
    ports:
    - "9446:9443"
  gateway-manager-2:
    image: docker.wso2.com/apim-pattern4-gateway-manager-2:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/gateway-manager-2/Dockerfile
    environment:
      - SLEEP=140
    ports:
    - "9449:9443"
  gateway-worker-2:
    image: docker.wso2.com/apim-pattern4-gateway-worker-2:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/gateway-worker-2/Dockerfile
    environment:
      - SLEEP=230
    ports:
    - "8281:8280"
    - "8244:8243"
    links:
      - gateway-manager-2
  publisher:
    image: docker.wso2.com/apim-pattern4-publisher:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/publisher/Dockerfile
    environment:
      - SLEEP=260
    ports:
      - "9445:9443"
  nginx:
    image: docker.wso2.com/apim-pattern4-nginx:2.1.0
    build:
      context: ../
      dockerfile: pattern-4/nginx/Dockerfile
    environment:
      - SLEEP=100
    ports:
      - "443:9443"
      - "80:9763"
#  nginx-lan2:
#    image: docker.wso2.com/apim-pattern4-nginx-lan2:2.1.0
#    build:
#      context: ../
#      dockerfile: pattern-4/nginx-lan2/Dockerfile
#    environment:
#      - SLEEP=60
#    ports:
#      - "9445:9443"
#      - "9765:9763"
