version: '2'
services:
  dbms:
    container_name: apim_rdbms
    build:
        context: .
        dockerfile: database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    container_name: svnrepo
    image: dockerhub.private.wso2.com/svnrepo
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      - SLEEP=100
    links:
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:apim-keymanager
  gateway-dmz:
    container_name: gateway-dmz
    build:
      context: .
      dockerfile: gateway-dmz/Dockerfile
    environment:
      - SLEEP=250
    links:
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:apim-keymanager
      - nginx-dmz:apim-external-store
  store:
    container_name: store
    build:
      context: .
      dockerfile: store/Dockerfile
    environment:
      - SLEEP=200
    links:
      - nginx-dmz:mgt.external.gw.apim.wso2.org
      - nginx-dmz:apim-external-gateway-worker
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-gateway-worker
      - nginx:apim-publisher
      - nginx:apim-keymanager
      - nginx-dmz:apim-external-store
  publisher:
    container_name: publisher
    build:
      context: .
      dockerfile: publisher/Dockerfile
    environment:
      - SLEEP=150
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx-dmz:mgt.external.gw.apim.wso2.org
      - nginx-dmz:apim-external-gateway-worker
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-keymanager
      - nginx-dmz:apim-external-store
  keymanager:
    container_name: keymanager
    build:
      context: .
      dockerfile: keymanager/Dockerfile
    environment:
      - SLEEP=400
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-keymanager
      - nginx:apim-gateway-worker
      - nginx:apim-store
  keymanager1:
    container_name: keymanager1
    build:
      context: .
      dockerfile: keymanager/Dockerfile
    environment:
      - SLEEP=50
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-keymanager
      - nginx:apim-gateway-worker
      - nginx:apim-store
  store-dmz:
    container_name: store-dmz
    build:
      context: .
      dockerfile: store-dmz/Dockerfile
    environment:
      - SLEEP=300
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-gateway-worker
      - nginx:apim-publisher
      - nginx:apim-keymanager
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      - SLEEP=100
    ports:
      - "9443:9443"
      - "9763:9763"
      - "7280:8280"
      - "7243:8243"
  nginx-dmz:
    container_name: nginx-dmz
    build:
      context: .
      dockerfile: nginx-dmz/Dockerfile
    environment:
      - SLEEP=100
    links:
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:mgt.gw.apim.wso2.org
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"

